### ISSUE TITLE
beforeRenderHeader hook

### ISSUE THREAD

**Issue by mpaul31** [someatoms/jsPDF-AutoTable#11]
not an issue but wanted to comment on something. the page split works beautifully but in my scenario i have to write some text before the table and in order to include this extra text in the page split i created a beforeRenderHeader method which takes in the doc and lastColPos.

could be handy!

**Comment by someatoms** [comment]
Sounds cool! Are you working on a pull request? I didn't really understand the difference between the beforeRenderHeader and the renderHeader methods however.

**Comment by mpaul31** [comment]
Not yet but it should probably be called beforeTableHeaderRow. Per table not page

**Comment by mpaul31** [comment]
Render not Row sorry

**Comment by someatoms** [comment]
Thats the best part! You can use the renderHeader method to insert a header for each table. You would just need to provide the correct startY position for each. It shouldn't be too hard as there is a `doc.autoTableEndPos()` method which returns the last rendering position of the last table.

**Comment by mpaul31** [comment]
Ah I thought that was for the page header only. Cool!

**Comment by someatoms** [comment]
Let me know if you run in to troubles!
