### ISSUE TITLE
Issue with Header Rendering

### ISSUE THREAD

**Issue by mpaul31** [someatoms/jsPDF-AutoTable#12]
hey buddy

every couple prints my output has a bug gap between the header and the table. do you see anything goofy going on in my code? like i said it works most of the time

var doc = new jsPDF('p', 'pt');
        var cols = [
            { title: "Food", key: "food" },
            { title: "Amount", key: "amount" },
            { title: "Serving Size", key: "servingSize" },
            { title: "Protein", key: "protein" },
            { title: "Carbs", key: "carbs" },
            { title: "Fat", key: "fat" },
            { title: "Calories", key: "calories" }
        ];

        doc.setFontSize(22);
        doc.text(day.name, 40, 40);
        doc.setFontSize(12);

        angular.forEach(day.sets, function (set) {
            angular.forEach(set.meals, function (meal) {
                var rows = [];
                angular.forEach(meal.items, function (item) {
                    var uom = _.find($scope.uomCache, function (uom) {
                        return uom.id === item.measurementId;
                    });
                    rows.push({
                        "food": item.food.name,
                        "amount": item.amount,
                        "servingSize": uom.name,
                        "protein": $filter('number')($scope.stats.forItem(item).protein.amount, 2),
                        "carbs": $filter('number')($scope.stats.forItem(item).carbohydrate.amount, 2),
                        "fat": $filter('number')($scope.stats.forItem(item).fat.amount, 2),
                        "calories": $filter('number')($scope.stats.forItem(item).totalCalories, 2),
                    });
                });
                rows.push({
                    "food": "Totals",
                    "amount": "",
                    "servingSize": "",
                    "protein": $filter('number')($scope.stats.forMeal(meal).protein.amount, 2),
                    "carbs": $filter('number')($scope.stats.forMeal(meal).carbohydrate.amount, 2),
                    "fat": $filter('number')($scope.stats.forMeal(meal).fat.amount, 2),
                    "calories": $filter('number')($scope.stats.forMeal(meal).totalCalories, 2),
                });

                if (angular.equals(meal, _.last(set.meals))) {
                    rows.push({
                        "food": "Grand Totals",
                        "amount": "",
                        "servingSize": "",
                        "protein": $filter('number')($scope.stats.forMealPlan().protein.amount, 2),
                        "carbs": $filter('number')($scope.stats.forMealPlan().carbohydrate.amount, 2),
                        "fat": $filter('number')($scope.stats.forMealPlan().fat.amount, 2),
                        "calories": $filter('number')($scope.stats.forMealPlan().totalCalories, 2),
                    });
                };

                var header = function (doc, pageCount, options) {
                    doc.setFontSize(12);
                    doc.text($scope.getSetOrdinalPdf(set, meal), 40, doc.autoTableEndPos().y - 5);
                    doc.setFontSize(options.fontSize);
                };

                var endPos = doc.autoTableEndPos();
                doc.autoTable(cols, rows, {
                    renderHeader: header,
                    startY: endPos ? endPos.y + 25 : 75,    //firstStartY
                    avoidPageSplit: true,
                    margins: { horizontal: 40, top: 40, bottom: 40 }
                });
            });
        });

        doc.save($scope.mealplan.name + ' (' + day.name + ').pdf');

**Comment by someatoms** [comment]
I can't see anything wrong by a quick look and it would take a lot of time for me to make your example runnable. Can you post a smaller runnable example which reproduces the issue? Preferably one without angular dependency and with example data.

**Comment by mpaul31** [comment]
Sure will post later

**Comment by mpaul31** [comment]
looks like the startY is not being reset between saves, so when the user clicks 'print' twice there is a huge gap. i'll keep digging around

**Comment by mpaul31** [comment]
which is strange even though i 'new' up a new instance of jsPDF

**Comment by someatoms** [comment]
This was a tricky one! I looked into the source and found that the API instance actually is static and it's state the same between jsPDF instances. I had to correct the plugin in a few ways, but this should now be fixed in version 1.2.1. Thanks for letting me know!

**Comment by mpaul31** [comment]
thanks man will give it a go! 

glad you were able to track it down

**Comment by someatoms** [comment]
Let me know how it goes!

**Comment by arnabk** [comment]
@simonbengtsson Is this issue resolved? I am facing this issue in current version.

```
console.log(111, doc.autoTableEndPosY());
        let options = {
            styles: {
                overflow: 'linebreak'
            },
            startY: doc.autoTableEndPosY() + 10
        };
        if (headerStyle || footerStyle) {
            options.addPageContent = function (data) {
                doc.setFontSize(headerStyle.fontSize || 15);
                doc.setTextColor(headerStyle.textColor || 40);
                doc.setFontStyle(headerStyle.fontStyle || 'normal');
                if (headerStyle)
                    doc.text(headerStyle.text || "", headerStyle.x || data.settings.margin.left, headerStyle.y || 60);
                if (footerStyle)
                    doc.text(footerStyle.text || '', headerStyle.x || data.settings.margin.left, headerStyle.y || doc.internal.pageSize.height - 30);
            };
        }
        if (noHeader) options.drawHeaderRow = () => false;
        options.styles = {overflow: 'linebreak'};
        options.bodyStyles = {valign: 'top'};
        options.margin = _.extend({}, margin);

        doc.autoTable(columns.map(m => m.name), rows, options);
```

When I call the above code multiple times, I see that its printing 50, 53, 103, 203, etc

Am I missing anything?

**Comment by simonbengtsson** [comment]
See #186. It is fixed but not released in a version yet. Will do it today or perhaps tomorrow.
