### ISSUE TITLE
How can I break lines instead of "ellipsise" them

### ISSUE THREAD

**Issue by pmainguet** [someatoms/jsPDF-AutoTable#14]
I have very long text that can't fit into one line (even in landscapte).
Is there a way to allow line breaks, increasing the height of the row to display full content ?

Would be a great addition (if it's not already included) in this great plugin.

**Comment by someatoms** [comment]
Unfortunately not possible right now. I actually started looking at how to implement it today, but realized it wasn't that easy and it might require some breaking changes. It's a great suggestion though and something that will be added at some point.

**Comment by pmainguet** [comment]
Thanks for your quick answer :-) I gonna look into it as well as it would be critical in the very near future for me. Please keep us posted on that, and thanks for the amazing work

**Comment by someatoms** [comment]
Added experimental support now! Use it by setting the option overflow to 'linebreak'. It might blow up since I haven't really tested it, but it works for a basic [example](https://someatoms.github.io/jsPDF-AutoTable/#long).

**Comment by pmainguet** [comment]
Thanks!

**Comment by someatoms** [comment]
No worries! Let me know if you have any issues.

**Comment by UlyssesAlves** [comment]
How can I find the source code for this example, please?

**Comment by someatoms** [comment]
In this repo in `examples/examples.js`. I looked through your [other issue](https://github.com/someatoms/jsPDF-AutoTable/issues/43) by the way, but didn't find anything wrong at first. Will take a deeper look soon.
