### ISSUE TITLE
Alignment for table cells

### ISSUE THREAD

**Issue by chip** [someatoms/jsPDF-AutoTable#16]
I'd like to right-justify some currency amounts and cannot figure out how to get it to work.  I tried your example, but altered the columns to have an `align` key like so:

```javascript
var columns = [
    {title: "ID", key: "id", align: "right"}, 
    {title: "Name", key: "name", align: "right"}, 
    {title: "Country", key: "country", align: "right"}, 
    {title: "Email", key: "email", align: "right"}
];
```

The PDF was generated successfully, but unfortunately the cell contents were not aligned like I specified.  Is this possible, and if so, how should I configure the options or column keys?

**Comment by someatoms** [comment]
Unfortunately there is no simple way of doing alignment and you have to manually calculate the text positions for now in the `renderCell` method. In the Custom Style example I made an example of center alignment. To simplify alignments is very high on the priority list however.

**Comment by chip** [comment]
Ok. Thanks for the tip. :smile:

**Comment by chip** [comment]
When I look at the Custom Style example PDF, I don't see anything centered.  What I'm trying to accomplish is right aligning currency data.  My initial thought was to do something like this:

```javascript
// Inside renderCell
doc.internal.pageSize.width - width
```

However, it appears that `width` represents cell width, not width of the actual text value. I'm having trouble finding documentation on the text object, so any suggestions would be appreciated. Thanks.

**Comment by someatoms** [comment]
I updated the advanced styling example with a right aligned currency table. It should work, however as mentioned this is harder than it should be and it will be easier to style tables in version 2.0. 

    // In renderCell
    // All cells with key 'currency' will be right aligned
    if (key === 'currency') {
        var strWidth = doc.getStringUnitWidth('' + value) * doc.internal.getFontSize();
        x += width;
        x -= 2 * settings.padding;
        x -= strWidth;
    }

**Comment by chip** [comment]
I had just cobbled this together from using the jsPDF API, which gave me a similar result:

```javascript
if (key === 'currency') {
  var textWidth = doc.getTextDimensions(value);
  var padding = settings.padding || 0;
  var margin = settings && settings.margins ? settings.margins.horizontal : 0;
  x = doc.internal.pageSize.width - textWidth.w - padding - margin;
}
```

However, I'll use your example since you have a lot more experience with this kind of work. :smile:

Thanks so much for your help!

**Comment by someatoms** [comment]
First of, no need to check if settings values exists. If not set by the user, I set default values for them. Second, your solution would only work for the right most column, but otherwise it looks good!

Some time ago I tested `getTextDimensions` versus using `getStringUnitWidth` and found that getStringUnitWidth was somewhat more exact. However, none of the them are perfect unfortunately.

**Comment by chip** [comment]
Thanks for the info.

**Comment by piersstorey** [comment]
Just in case someone finds this issue. I've used a solution shown here: https://jsfiddle.net/j9vaqpnz/10/
