### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by jdr430** [someatoms/jsPDF-AutoTable#17]
Using google chrome I tried to run he script and recieved the following error pointing at line 12 of jspd.plugin.autotable.js
`Uncaught TypeError: Cannot read property 'events' of undefined`. And because of this the `autoTable` function in unrecognised. How do I fix this?

**Comment by someatoms** [comment]
Sounds strange, it would indicate that the API instance is not set. Could you post the code you are using?

**Comment by jdr430** [comment]
I tried using my own code but that didn't work so i'm just trying it with your example to see if it works. The code:
`$(document).on("click", "#PDF", function () {
	  var columns = [
	                 {title: "ID", key: "id"}, 
	                 {title: "Name", key: "name"}, 
	                 {title: "Country", key: "country"}, 
	                 {title: "Email", key: "email"}
	             ];
	             var data = [
	                 {"id": 1, "name": "Shaw", "country": "Tanzania", "email": "abrown@avamba.info"},
	                 {"id": 2, "name": "Nelson", "country": "Kazakhstan", "email": "jjordan@agivu.com"},
	                 {"id": 3, "name": "Garcia", "country": "Madagascar", "email": "jdean@skinte.biz"}
	       
	             ];

	             var doc = new jsPDF('p', 'pt');
	             doc.autoTable(columns, data, {});
	             doc.save('table.pdf');
});`

**Comment by someatoms** [comment]
Strange! That code works for me. Check out this fiddle: https://jsfiddle.net/someatoms/buLugtcc/

**Comment by jdr430** [comment]
Hmm I noticed you're using JQuery 2.1.3 I am using 1.11.2.min could that be why??

**Comment by jdr430** [comment]
# Update New error:
So i did A fresh install of jsPDF as I figured that could be the issue which eliminated the initial error. However when I click the button to generate the `pdf` file I get a new error pointing at line 315.

```
Uncaught TypeError: undefined is not a function
```

**Comment by jdr430** [comment]
Can't seem to fix this error:
```
Uncaught TypeError: undefined is not a functionjspdf.plugin.autotable.js:39 defaultOptions.renderHeaderCelljspdf.plugin.autotable.js:233 (anonymous function)jspdf.plugin.autotable.js:230 printHeaderjspdf.plugin.autotable.js:88 API.autoTable(index):1204 (anonymous function)jquery-1.11.2.min.js:3 m.event.dispatchjquery-1.11.2.min.js:3 m.event.add.r.handle
```
On this line :
```
  y += settings.lineHeight / 2 + doc.internal.getLineHeight() / 2;
```

**Comment by someatoms** [comment]
It seems to be a problem with your setup. Can you try to reproduce the issue in a jsfiddle or send me your entire project?

**Comment by jdr430** [comment]
I can't create it on Fiddle, how do I send it to you?

**Comment by someatoms** [comment]
Add it here.

**Comment by jdr430** [comment]
https://jsfiddle.net/jdr430/Lqgm0g77/

**Comment by someatoms** [comment]
In the jsFiddle you need to include the jspdf before the autotable plugin, like in the jsfiddle I posted.

**Comment by jdr430** [comment]
I can't see jsPDF in the fiddle you posted but this is how I included it on my project:

```
<script type="text/javascript"
	src="dummydisc/disc/scripts/jsPDF/jspdf.js"></script>
<script type="text/javascript"
	src="dummydisc/disc/scripts/jspdf.plugin.autotable.js"></script>
<script type="text/javascript"
	src="dummydisc/disc/scripts/jsPDF/jspdf.plugin.split_text_to_size.js"></script>
<script type="text/javascript"
	src="dummydisc/disc/scripts/jsPDF/jspdf.plugin.cell.js"></script>
<script type="text/javascript"
	src="dummydisc/disc/scripts/jsPDF/jspdf.plugin.from_html.js"></script>
<script type="text/javascript"
	src="dummydisc/disc/scripts/jsPDF/jspdf.plugin.javascript.js"></script>
<script type="text/javascript"
	src="dummydisc/disc/scripts/jsPDF/jspdf.plugin.sillysvgrenderer.js"></script>
<script type="text/javascript"
	src="dummydisc/disc/scripts/jsPDF/jspdf.plugin.standard_fonts_metrics.js"></script>
<script type="text/javascript"
	src="dummydisc/disc/scripts/jsPDF/jspdf.plugin.addimage.js"></script>
<script type="text/javascript"
	src="dummydisc/disc/scripts/jsPDF/jspdf.PLUGINTEMPLATE.js"></script>
```
Am I missing anything??

**Comment by jdr430** [comment]
Sorry about this I just realised the order was wrong. It now works fine I needed to place the debug before autotable. Thanks you can close this, sorry for time-wasting

**Comment by someatoms** [comment]
No worries, let me know if run into other issues!

**Comment by jdr430** [comment]
I am going to post here since I don't want to open another issue. This is regarding converting table to JSON, I am using the code below:

```
$(document).on("click", "#PDF", function () {
	var doc = new jsPDF('p', 'pt');
	 var result = doc.autoTable(false, doc.autoTableHtmlToJson($('#result')));
	 console.log(result);

	       
});

```
I get this error when I run it:
```
Uncaught TypeError: Cannot read property '0' of undefined
```
On line 121. Is my syntax correct?

**Comment by snehalatapimprale** [comment]
Hi, 
I used following code and I am getting error
EXCEPTION: Error in ./AppComponent class AppComponent - inline template:6:12 caused by: this.internal.getCurrentPageInfo is not a function

I tried following code , please suggest what I missed
import { Component } from '@angular/core';
declare let jsPDF:any; 
@Component({
  selector: 'my-app',
  template: `
            <button (click)="trythis()">click</button>`
})
export class AppComponent{
 cols:any=[
  {headerName: "NAME", field: "name", width: 250}, 
  {headerName: "AGE", field: "age", width: 250},
  {headerName: "GENDER", field: "gender", width: 250}
  ];
  rows:any=[
  {name: "Geller", age: 30, gender: "Male"},
  {name: "Geller", age: 28, gender: "Female"},
  {name: "Tribbiani", age: 29, gender: "Male"},
  {name: "Bing", age: 30, gender: "Male"},
  {name: "Green", age: 28, gender: "Female"},
  {name: "Buffay", age: 29, gender: "Female"}
  ];
   trythis() {
    var doc = new jsPDF('p', 'pt');
    doc.autoTable(this.cols, this.rows);
    doc.save("table.pdf")
  }
}
