### ISSUE TITLE
Meteor integration

### ISSUE THREAD

**Issue by chip** [someatoms/jsPDF-AutoTable#19]
After publishing your package for Meteor on [Atmosphere](https://atmospherejs.com/chipcastledotcom/jspdf-autotable) recently, I've noticed a push by other developers in the Meteor community to get [Official Integration](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/Known-Attempts-to-get-Official-Integration).

This would more than likely require me to issue a PR that only includes a `package.js` and `package.json` file suitable for the Meteor community. Since I am considering doing this for a number of repos, I wanted to create an issue for this and see which repo maintainers would consider merging this work.

Thanks for creating this library. It's been a huge help on my projects and others have benefitted from it as well.

Please let me know if you're interested in having me move forward with this effort.

Thanks again,
Chip

/cc @splendido @dandv

**Comment by someatoms** [comment]
Sure, sounds like a good idea!

**Comment by chip** [comment]
Do you have a preference for an organization name under which this repo would be stored?

For example, my original package was referred to as `chipcastledotcom:jspdf-autotable`, where `chipcastledotcom` was the organization name and `jspdf-autotable` is the package. For your package it will be different since I'll be deprecating the original.

It's basically a namespacing issue, but since it's your package, I'll wanted to give you first shot at naming it.

**Comment by splendido** [comment]
hi guys!

..what if we were to keep a `jspdf` organization name and put all related plugin packages under it?
In this case this would become `jspdf:auto-table`

Thoughts?

**Comment by someatoms** [comment]
Sounds good to me!

**Comment by chip** [comment]
Cool! Thank you. :+1:

**Comment by chip** [comment]
Wow guys, this is exciting news! :+1: 

@splendido - As an update, from the command line this works great:

```
meteor search autotable
Matching packages:                            
chipcastledotcom:jspdf-autotable  Meteor package for AutoTable plugin to jsPDF
jspdf:autotable                   Official PDF table generator in javascript (jspdf plugin)
```

I'm planning to deprecate `chipcastledotcom:jspdf-autotable` and point it to the official package, but I noticed that I don't get similar results when using Atmosphere. What steps are remaining before this goes live there?

@someatoms - Thanks so much for writing this plugin and for your super responsive support throughout the process!

**Comment by simonbengtsson** [comment]
Right now version `1.3.0` is posted on atmosphere while the newest version is `2.1.0`. I suggest that we deprecate this package by calling `meteor admin set-unmigrated` so that it does not show up in search. I don't think that a version on atmosphere is needed anymore as it seems like the atmosphere community has mostly moved to npm.

I also think that we should deprecate the `jspdf:core` package as it also is outdated.

An issue was just resolved regarding this issue #183.

**Comment by chip** [comment]
@simonbengtsson - Thanks, I just executed your suggestion...
```
Logged in as... Thanks for being a Meteor developer!
 ~/code/jspdf-core-wrapper master ✔ 
$ meteor admin set-unmigrated jspdf:core
done.                                         igrated ...                                               
done.                                         igrated ...                                               
 ~/code/jspdf-core-wrapper master ✔ 
$ meteor admin set-unmigrated jspdf:autotable
done.                                         y migrated ... 
```  

Looks like it worked, but the search still returns results for `jspdf:core`:

```
$ meteor search jspdf
Matching packages:                            
jspdf:core             jsPDF (official): Generate PDF files on the client-side
local-test:jspdf:core  jsPDF (official): Generate PDF files on the client-side

You can use 'meteor show' to get more information on a specific item.
 ~/code/jspdf-core-wrapper master ✔ 
$ meteor search jspdf:autotable
jspdf:autotable: nothing found
```

Not sure what else to do for core. Maybe @splendido has a suggestion?

**Comment by simonbengtsson** [comment]
Neither `jspdf:core` nor `jspdf-autotable` shows up in search now for me. Perfect! Thanks!
