### ISSUE TITLE
Content before autotable

### ISSUE THREAD

**Issue by czegarram** [someatoms/jsPDF-AutoTable#2]
¿Is there a way to add a title and some text before autotable?

**Comment by someatoms** [comment]
Better support for this was released in version 1.0. An example "With content" also exist in `/examples/examples.js`.

**Comment by BeckhamVinoth** [comment]
Hi Simon , How to add two sentences in pageBeforeContent ? Ex : 1). content  X                                                                             
                                                                                                           2) content Y .
is it possible huh ?

**Comment by simonbengtsson** [comment]
Not sure what you mean. If you have a question about how to do something with the plugin it would be easier if you created a question on stackoverflow with more information. I actively monitor the `jspdf-autotable` tag.

**Comment by BeckhamVinoth** [comment]
beforePageContent: function(data) {
                	    	doc.setFontSize(12);
                	    	doc.setFont("courier");
                	     doc.text("Content X " ,20, 15);
                              doc.text("Content Y" ,20, 15);

What am trying to do here is , Printing the Content Y in the next line of Content Y , But it's getting Overlapped 
                	        
                	        
                	    },

**Comment by simonbengtsson** [comment]
Aha! Make sure you use the [doc.text](http://mrrio.github.io/doc/symbols/jsPDF.html#.text) function correctly. Its signature is like this `jsPDF.text(x, y, text)`.

**Comment by BeckhamVinoth** [comment]
Yes man , You are right . I just Misunderstood that . Thanks Buddy @simonbengtsson

**Comment by Krenabothu** [comment]
doc.text(400, 50, "Daily View");
  doc.autoTable({
      headStyles: { fontSize: 10, headerBackgroundColor:"red" },
      backgroundColor:"red",
      bodyStyles: { fontSize: 8 },
    head: [filedNames],
    body: dailyRows,
    // options
    // ...
  });



  doc.text("Weekly View", 400, doc.autoTable.previous.finalY + 10);
  doc.autoTable({
    headStyles: { fontSize: 10},
    bodyStyles: { fontSize: 8},
    head: [filedNames],
    body: weeklyRows,
    // options
    // ...
  });
