### ISSUE TITLE
Saving to server

### ISSUE THREAD

**Issue by jdr430** [someatoms/jsPDF-AutoTable#21]
I am trying to save the generated pdf file to the server using the following code : 

```
$(document).on("click", "#PDF", function () {
    var table = document.getElementById("result");
    var tbl = window.sessionStorage.getItem("tbl");
    var cols = [],
        data = [];

    function html() {
        var doc = new jsPDF('p', 'pt');
        var res = doc.autoTableHtmlToJson(table, true);
        doc.autoTable(res.columns, res.data);
        var pdf =doc.output('arraybuffer');
     	console.log(pdf)
        var data = new FormData();
        data.append("data" , pdf);
        var xhr = new XMLHttpRequest();
        xhr.open( 'post', 'upload.php', true );
        xhr.send(data);    
    }

    html();
});
```
Then using the following server script to write to the file.
```

if(!empty($_POST['data'])){
	$data = $_POST['data'];
	echo $data;
	$fname = "test.pdf";//generates random name
	$file = fopen("testa/pdf/" .$fname, 'w');//creates new file
	fwrite($file, $data);
	fclose($file);
} else {
	echo "No Data Sent";
}
```
The problem I have is, I am able to save a `test_.pdf` file on my server but I can't open it because I think its not a valid `.pdf` file. Request Payload of my `upload.php` Header  returns the following : 
```
------WebKitFormBoundarySMKgD1d2FOKOoivZ
Content-Disposition: form-data; name="data"

[object ArrayBuffer]
------WebKitFormBoundarySMKgD1d2FOKOoivZ--
```
Preview : 

```
[]
No Properties
```
So it seems like `doc.output('arraybuffer')` sends an empty data set. How can I grab the data from `doc`  and pass it on to my PHP script?

**Comment by someatoms** [comment]
Sweet!

**Comment by bryann-and** [comment]
when i use this method, the PDF file saves is corrupted and only 3Kb of size, but when i choose to download that same file with doc.save() i get a file with ~6Mb.
this is the php file i'm using:

'<?php

    if(!empty($_POST['data'])){
    $data = $_POST['data'];
    $fname = "certificado.pdf"; 
    $file = fopen("certificado/" .$fname, 'w');
    fwrite($file, $data);
    fclose($file);
?>

any ideas?

**Comment by malanvanwyk** [comment]
bryann-and

If your pdf design has any lines or graphics from jspdf like. doc.line(10,100,200,100) the pdf will get corrupted when trying to send it this way.

I have been looking for a solution as well with no luck. Hope someone can figure out a solution.
