### ISSUE TITLE
publish / savedAs is not defined.

### ISSUE THREAD

**Issue by jonas89** [someatoms/jsPDF-AutoTable#22]
Hi! Ive stumbled across a problem, that i'm struggeling to figure out.
I keep getting told that publish / savedAs is not defined(tryed both obviously).

code: 

var doc = new jsPDF('p', 'pt');
                    doc.autoTable(addedAttributes, exportData, {});
                    doc.save('table.pdf');

this is wrapped inside a click event.

JS files( jsPDF files only)

                        "~/Scripts/jsPDF2/jspdf.js",
                        "~/Scripts/jsPDF2/jspdf.plugin.standard_fonts_metrics.js",
                        "~/Scripts/jsPDF2/jspdf.plugin.split_text_to_size.js",
                        "~/Scripts/jsPDF2/jspdf.plugin.from_html.js",
                        "~/Scripts/jsPDF2/jspdf.plugin.cell.js",
                        "~/Scripts/jsPDF2/jspdf.plugin.autotable.js",
                        "~/Scripts/jsPDF2/jspdf.plugin.annotations.js",
                        "~/Scripts/jsPDF2/jspdf.plugin.addimage.js",
                        "~/Scripts/jsPDF2/jspdf.autoprint.js",

Is there any special dependacies appart from these files?

**Comment by someatoms** [comment]
Did you solve your issue?

**Comment by jonas89** [comment]
Hi there, thx for replying :) Yes i did. I kept getting the error saveAs is not defined, when doing "doc.save("someName.pdf");"

In the end i figured id try to include the debug file from ur example files. And now it does work.

Im pretty new to JS in general, so im not sure why that would help, but i saw there was some "cases" defined in that document, in which "saveAs" was mentioned.

**Comment by someatoms** [comment]
Nice! The reason including only the debug file works is because that file is basically just a concatenation of all the files you included manually (plus a little extra as you found out). Using jspdf I would recommend you to use either the the debug file or the minified debug file from the dist folder in the [jspdf repository](https://github.com/MrRio/jsPDF). If you have other issues, let me know!

**Comment by jonas89** [comment]
Thx, ur the best!
