### ISSUE TITLE
Word wrap in cell

### ISSUE THREAD

**Issue by Jkrish001** [someatoms/jsPDF-AutoTable#23]
Hi, 
     How can i implement wrapping in long sentences. Line height is not a problem.

**Comment by someatoms** [comment]
Hi! Check out the long text example in the `examples/examples.js` and the [demo page](https://someatoms.github.io/jsPDF-AutoTable/#long) for how it looks like. Basically you can set the overflow option to linebreak, like this:

    
    var cols = [
        {title: "ID", key: "id"},
        {title: "Name", key: "first_name"},
        ...
    ];
    var data = [{
        "id": 1,
        "first_name": "Russell",
        ...
    }, {
        "id": 2,
        "first_name": "Laura",
        ....
    }];

    doc.autoTable(cols, data, {overflow: 'linebreak'});

**Comment by someatoms** [comment]
I hope my answer solved your issue. If not, feel free to open the issue again.
