### ISSUE TITLE
Specific column format

### ISSUE THREAD

**Issue by pmainguet** [someatoms/jsPDF-AutoTable#24]
Hello!

I'm wondering if there is a simple way to give a specific format to only one column of the table (apply bold font for example or add red background) ?

And keep the good work! Lovin' this plugin the more I use it!

**Comment by someatoms** [comment]
Simple is always relative, but you can check out the `custom style` example where I am styling specific columns. It basically involves checking the key parameter and apply and custom styling only if the key matches your specific column. Something like this:

    if (key === 'expenses') {
        doc.setFillColor(240, 0, 240);
    }

**Comment by pmainguet** [comment]
but simple it is :-)
Thanks man

**Comment by someatoms** [comment]
No worries! Let me know if you have other issues!
