### ISSUE TITLE
Double table in a PDF file

### ISSUE THREAD

**Issue by XinYiMan** [someatoms/jsPDF-AutoTable#25]
Hello, I need to enter two tables in a PDF file, and I wrote the following code, only it does not work very well. Why Writes the second table, between the second and the last line of the first table
![document-0](https://cloud.githubusercontent.com/assets/10870676/7414457/37d071b2-ef53-11e4-9884-bccb558ce6db.png)
![document-1](https://cloud.githubusercontent.com/assets/10870676/7414464/3f636952-ef53-11e4-94c2-9c4ec144a7dc.png)

Why?
My code:

			function generatefromtable(intestazione) {
				try{
					var $ret=true;
					var totalPagesExp = "{total_pages_count_string}";
				    //var doc = new jsPDF('p', 'pt');
					var doc = new jsPDF('l', 'pt', 'a4', true); 
				    var header = function (doc, pageCount, options) {
					doc.setFontSize(20);
					doc.text(intestazione, options.margins.horizontal, 60);
					doc.setFontSize(options.fontSize);
				    };

				    var footer = function (doc, lastCellPos, pageCount, options) {
					var str = " " + pageCount + "/" + totalPagesExp;
					doc.text(str, options.margins.horizontal, doc.internal.pageSize.height - 30);
				    };
				    var options = {renderHeader: header, renderFooter: footer, margins: {horizontal: 40, top: 80, bottom: 50}};    

				    // Be sure to set the second parameter (indexBased option) to true
				    // It will be the default behavior in v2.0, but are now behind an option for compatibility
				    var res = doc.autoTableHtmlToJson(document.getElementById("tbl"), true);
				    doc.autoTable(res.columns, res.data, options);

				    var res2 = doc.autoTableHtmlToJson(document.getElementById("tbl_resoconto"), true);
				    doc.autoTable(res2.columns, res2.data, options);

   				    doc.putTotalPages(totalPagesExp);

				    doc.output("dataurlnewwindow");

				}catch(err) {
			    		//err.message per avere il testo del messaggio
					ret=false;
				}

				return ret;
			}

**Comment by someatoms** [comment]
That sounds interesting, can you provide the html of the tables as well. I can't debug right now, but will have a look at it tonight.

**Comment by XinYiMan** [comment]
My html code

<table class="table table-bordered table-hover" id="tbl"><thead>    <tr>      <th>CONTO</th>      <th>DESCRIZIONE</th>      <th>DARE</th>      <th>AVERE</th>      <th>SALDO_DARE</th>      <th>SALDO_AVERE</th>      <th>TIPO</th>      <th>CENTROCOSTO</th>    </tr>  </thead>  <tbody style="font-size: 9px;">    <tr>      <td>0801002</td>      <td>IVA C/ACQUISTI</td>      <td align="right">170,61</td>      <td align="right">4,90</td>      <td align="right">165,71</td>      <td align="right">0,00</td>      <td>PA</td>      <td></td>    </tr>    <tr>      <td>0801003</td>      <td>IVA differita c/acquisti</td>      <td align="right">100,03</td>      <td align="right">6,86</td>      <td align="right">93,17</td>      <td align="right">0,00</td>      <td>PA</td>      <td></td>    </tr>    <tr>      <td>1250001</td>      <td>ASSEGNI</td>      <td align="right">32,00</td>      <td align="right">0,00</td>      <td align="right">32,00</td>      <td align="right">0,00</td>      <td>PA</td>      <td></td>    </tr>    <tr>      <td>1250030</td>      <td>CASSA CONTANTE</td>      <td align="right">26,00</td>      <td align="right">80,00</td>      <td align="right">0,00</td>      <td align="right">54,00</td>      <td>PA</td>      <td></td>    </tr>    <tr>      <td>8000000001</td>      <td>#Cliente di Prova</td>      <td align="right">177,47</td>      <td align="right">60,50</td>      <td align="right">116,97</td>      <td align="right">0,00</td>      <td>CL</td>      <td></td>    </tr>    <tr>      <td>8000000003</td>      <td>#Ditta XYZ Srl</td>      <td align="right">487,00</td>      <td align="right">0,00</td>      <td align="right">487,00</td>      <td align="right">0,00</td>      <td>CL</td>      <td></td>    </tr>    <tr>      <td>8000000004</td>      <td>#Azienda agricola Metanolo &amp; Vino</td>      <td align="right">12,10</td>      <td align="right">6,05</td>      <td align="right">6,05</td>      <td align="right">0,00</td>      <td>CL</td>      <td></td>    </tr>    <tr>      <td>8000000005</td>      <td>Ditta nuova tutta per me</td>      <td align="right">64,13</td>      <td align="right">0,00</td>      <td align="right">64,13</td>      <td align="right">0,00</td>      <td>CL</td>      <td></td>    </tr>    <tr>      <td>2601005</td>      <td>IVA C/VENDITE</td>      <td align="right">5,95</td>      <td align="right">116,75</td>      <td align="right">0,00</td>      <td align="right">110,80</td>      <td>PP</td>      <td></td>    </tr>    <tr>      <td>2601007</td>      <td>IVA C/CORRISPETTIVI</td>      <td align="right">0,00</td>      <td align="right">7,42</td>      <td align="right">0,00</td>      <td align="right">7,42</td>      <td>PP</td>      <td></td>    </tr>    <tr>      <td>2601008</td>      <td>IVA differita c/vendite</td>      <td align="right">3,50</td>      <td align="right">37,03</td>      <td align="right">0,00</td>      <td align="right">33,53</td>      <td>PP</td>      <td></td>    </tr>    <tr>      <td>3001001</td>      <td>BANCA A C/C</td>      <td align="right">50,41</td>      <td align="right">47,93</td>      <td align="right">2,48</td>      <td align="right">0,00</td>      <td>PS</td>      <td></td>    </tr>    <tr>      <td>3001003</td>      <td>BANCA A c/pagamenti</td>      <td align="right">0,00</td>      <td align="right">23,39</td>      <td align="right">0,00</td>      <td align="right">23,39</td>      <td>PS</td>      <td></td>    </tr>    <tr>      <td>3025115</td>      <td>CONTO DI GIRO TRANSITORIO</td>      <td align="right">8,07</td>      <td align="right">8,07</td>      <td align="right">0,00</td>      <td align="right">0,00</td>      <td>PS</td>      <td></td>    </tr>    <tr>      <td>2200000007</td>      <td>Ditta di prova</td>      <td align="right">0,00</td>      <td align="right">242,00</td>      <td align="right">0,00</td>      <td align="right">242,00</td>      <td>FR</td>      <td></td>    </tr>    <tr>      <td>2200000041</td>      <td>Computer Systems di Mattarei Valentina</td>      <td align="right">0,00</td>      <td align="right">60,50</td>      <td align="right">0,00</td>      <td align="right">60,50</td>      <td>FR</td>      <td></td>    </tr>    <tr>      <td>22000000SL</td>      <td>Screenleap Inc.</td>      <td align="right">20,00</td>      <td align="right">110,00</td>      <td align="right">0,00</td>      <td align="right">90,00</td>      <td>FR</td>      <td></td>    </tr>    <tr>      <td>9000000001</td>      <td>#Fornitore di Prova</td>      <td align="right">0,00</td>      <td align="right">780,00</td>      <td align="right">0,00</td>      <td align="right">780,00</td>      <td>FR</td>      <td></td>    </tr>    <tr>      <td>9000000002</td>      <td>#zzz fornitore antipatico</td>      <td align="right">39,52</td>      <td align="right">359,56</td>      <td align="right">0,00</td>      <td align="right">320,04</td>      <td>FR</td>      <td></td>    </tr>    <tr>      <td>9000000005</td>      <td>Uccell di bosco</td>      <td align="right">0,00</td>      <td align="right">96,80</td>      <td align="right">0,00</td>      <td align="right">96,80</td>      <td>FR</td>      <td></td>    </tr>    <tr>      <td>4201001</td>      <td>MERCI C/ACQUISTI</td>      <td align="right">900,00</td>      <td align="right">0,00</td>      <td align="right">900,00</td>      <td align="right">0,00</td>      <td>EC</td>      <td></td>    </tr>    <tr>      <td>4201090</td>      <td>ONERI ACCESSORI SU MERCI</td>      <td align="right">123,00</td>      <td align="right">0,00</td>      <td align="right">123,00</td>      <td align="right">0,00</td>      <td>EC</td>      <td></td>    </tr>    <tr>      <td>4220030</td>      <td>SPESE LEGALI</td>      <td align="right">200,00</td>      <td align="right">0,00</td>      <td align="right">200,00</td>      <td align="right">0,00</td>      <td>EC</td>      <td></td>    </tr>    <tr>      <td>4220035</td>      <td>SPESE DI BANCA</td>      <td align="right">1,55</td>      <td align="right">0,00</td>      <td align="right">1,55</td>      <td align="right">0,00</td>      <td>EC</td>      <td></td>    </tr>    <tr>      <td>4220068</td>      <td>SPESE PER SITI/SERVIZI INTERNET</td>      <td align="right">110,00</td>      <td align="right">20,00</td>      <td align="right">90,00</td>      <td align="right">0,00</td>      <td>EC</td>      <td></td>    </tr>    <tr>      <td>4250010</td>      <td>IMPOSTA DI BOLLO</td>      <td align="right">80,00</td>      <td align="right">0,00</td>      <td align="right">80,00</td>      <td align="right">0,00</td>      <td>EC</td>      <td></td>    </tr>    <tr>      <td>4270025</td>      <td>ONERI E PERDITE VARIE</td>      <td align="right">50,00</td>      <td align="right">10,00</td>      <td align="right">40,00</td>      <td align="right">0,00</td>      <td>EC</td>      <td></td>    </tr>    <tr>      <td>4270035</td>      <td>COSTI INDEDUCIBILI</td>      <td align="right">25,00</td>      <td align="right">0,00</td>      <td align="right">25,00</td>      <td align="right">0,00</td>      <td>EC</td>      <td></td>    </tr>    <tr>      <td>7201001</td>      <td>MERCI C/VENDITE</td>      <td align="right">0,00</td>      <td align="right">168,00</td>      <td align="right">0,00</td>      <td align="right">168,00</td>      <td>ER</td>      <td></td>    </tr>    <tr>      <td>7201002</td>      <td>MERCI C/VENDITE AL DETTAGLIO</td>      <td align="right">10,00</td>      <td align="right">450,58</td>      <td align="right">0,00</td>      <td align="right">440,58</td>      <td>ER</td>      <td></td>    </tr>  </tbody></table>
<table style="width: 50%;" class="table table-bordered table-hover" id="tbl_resoconto"><thead>    <tr>	<th>Descr. voce bilancio</th>	<th>Importo</th>    </tr>  </thead>  <tbody><tr><td>TOTALE ATTIVO PATRIMONIALE: </td><td align="right">967,51</td></tr><tr><td>TOTALE PASSIVO PATRIMONIALE: </td><td align="right">1.818,48</td></tr><tr><td>TOTALE A PAREGGIO: </td><td align="right">-850,97</td></tr><tr><td>TOTALE CONTI D'ORDINE: </td><td align="right">0,00 * 0,00</td></tr><tr><td>TOTALE RICAVI: </td><td align="right">1.459,55</td></tr><tr><td>TOTALE COSTI: </td><td align="right">608,58</td></tr><tr><td>RISULTATO DI ESERCIZIO: </td><td align="right">850,97</td></tr>  </tbody></table>

**Comment by someatoms** [comment]
The AutoTable plugin doesn't automatically set the `startY` position of the next table. This has to be done manually in the current plugin version. To fix your issue you can set the `startY` position to the endpos of the last drawn cell of the plast table plus the space you want between the tables. Something like this:

    var lastPosY = doc.autoTableEndPosY();
    options.startY = lastPosY + 50;

I made a jsFiddle [here](https://jsfiddle.net/someatoms/mhzex91n/2/) with your complete code and the fix above for reference, but you can also check the multiple tables example. 

Let me know if you have further issues!

**Comment by XinYiMan** [comment]
Thanks, it works great :)

Can I ask you to give me an answer to another question I asked in the post? Thank you're an angel

**Comment by RajarshiSaha1985** [comment]
Hi,
Using jspdf-autoTable 3.1.1 and jspdf 1.5.3, why a gap is coming between two autotables passing margin object :

First Table: 
margin: {top: 10, right: 14, bottom: 0, left: 14}

Second Table:
margin: {top: 20, right: 14, bottom: 0, left: 14}

Thanks in advance.
