### ISSUE TITLE
Right aligned columns and display some contents in full

### ISSUE THREAD

**Issue by XinYiMan** [someatoms/jsPDF-AutoTable#26]
Hello I wanted to know two things, I have a column that I will always display its contents in full, see the attached file in column 2.

I also want that the columns with the numbers with commas are aligned right. See column 6 of the attached file.

thanks
![document](https://cloud.githubusercontent.com/assets/10870676/7414747/ec38b6cc-ef54-11e4-9582-4a6c39f24fb7.png)

**Comment by someatoms** [comment]
You can check out the `long text` example to always display some columns in full. It involves setting all columns in the `overflowColumns` option. 

Aligning text to the right has to be done manually right now in the renderCell function. You can check the custom style example for an example.

**Comment by XinYiMan** [comment]
Hello, I tried for the size of the column, and I do not work, this is my code:

			function generatefromtable(intestazione) {
				try{
					var $ret=true;
					var totalPagesExp = "{total_pages_count_string}";
				    //var doc = new jsPDF('p', 'pt');
					var doc = new jsPDF('l', 'pt', 'a4', true); 
				    var header = function (doc, pageCount, options) {
					doc.setFontSize(20);
					doc.text(intestazione, options.margins.horizontal, 60);
					doc.setFontSize(options.fontSize);
				    };

				    var footer = function (doc, lastCellPos, pageCount, options) {
					var str = " " + pageCount + "/" + totalPagesExp;
					doc.text(str, options.margins.horizontal, doc.internal.pageSize.height - 30);
				    };
				    var options = {renderHeader: header, renderFooter: footer, margins: {horizontal: 40, top: 80, bottom: 50,overflowColumns: ['CODICE']}};    

				    // Be sure to set the second parameter (indexBased option) to true
				    // It will be the default behavior in v2.0, but are now behind an option for compatibility
				    var res = doc.autoTableHtmlToJson(document.getElementById("tbl_daStampare"), true);

				    doc.autoTable(res.columns, res.data, options);
   				    doc.putTotalPages(totalPagesExp);

				    doc.output("dataurlnewwindow");

				}catch(err) {
			    		//err.message per avere il testo del messaggio
					ret=false;
				}

				return ret;
			}
This is my html

<div class="container" width="200px" heigth="200px" id="div_tbl"><table class="table table-bordered table-hover" id="tbl_daStampare"><thead>    <tr>      <th title="DATASCAD" key="DATASCAD">DATA SCAD.</th>      <th title="CODICE" key="CODICE">CODICE</th>      <th title="DESCRIZIONE" key="DESCRIZIONE">DESCR.</th>      <th title="NUMDOC" key="NUMDOC">NUM. DOC.</th>      <th title="DATADOC" key="DATADOC">DATA DOC.</th>      <th title="IMPORTO" key="IMPORTO">IMPORTO</th>      <th title="ABILITA_PAG" key="ABILITA_PAG">SEL.</th>      <th title="TIPOPAG" key="TIPOPAG">TIPO PAG.</th>      <th title="CONDPAGAM" key="CONDPAGAM">COND: PAG.</th>      <th title="COD_BANCA" key="COD_BANCA">BANCA</th>      <th title="PROTOCOLLO" key="PROTOCOLLO">PROT.</th>    </tr>  </thead>  <tbody style="font-size: 9px;">    <tr>      <td>03/03/2012</td>      <td>=====</td>      <td>Ditta XYZ</td>      <td>INTERESSI DI DILAZIO</td>      <td>03/03/2012</td>      <td align="right">50,00</td>      <td>0</td>      <td>BB</td>      <td>BB</td>      <td>CRTN</td>      <td></td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>02/03/2012</td>      <td>=====</td>      <td>Ditta ABC</td>      <td>RATA PIANO DI RIENTR</td>      <td>02/03/2012</td>      <td align="right">100,00</td>      <td>0</td>      <td>BB</td>      <td>BB</td>      <td>CR1</td>      <td></td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>28/02/2014</td>      <td>8000000003</td>      <td>#Ditta XYZ Srl</td>      <td>00/1</td>      <td>02/02/2014</td>      <td align="right">122,00</td>      <td>0</td>      <td>RI</td>      <td>RI0</td>      <td>CR1</td>      <td>1</td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>31/03/2012</td>      <td>8000000001</td>      <td>#Cliente di Prova</td>      <td>00/1</td>      <td>02/01/2012</td>      <td align="right">40,33</td>      <td>0</td>      <td>RB</td>      <td>R369</td>      <td>CR1</td>      <td>1</td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>30/04/2012</td>      <td>8000000001</td>      <td>#Cliente di Prova</td>      <td>00/1</td>      <td>02/01/2012</td>      <td align="right">40,34</td>      <td>0</td>      <td>RB</td>      <td>R369</td>      <td>CR1</td>      <td>1</td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>15/03/2014</td>      <td>8000000003</td>      <td>#Ditta XYZ Srl</td>      <td>00/2</td>      <td>15/02/2014</td>      <td align="right">244,00</td>      <td>0</td>      <td>RI</td>      <td>RI0</td>      <td>CR1</td>      <td>2</td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>30/04/2012</td>      <td>8000000001</td>      <td>#Cliente di Prova</td>      <td>00/2</td>      <td>02/03/2012</td>      <td align="right">4,03</td>      <td>0</td>      <td>RB</td>      <td>R369</td>      <td>CR1</td>      <td>2</td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>30/06/2012</td>      <td>8000000001</td>      <td>#Cliente di Prova</td>      <td>00/2</td>      <td>02/03/2012</td>      <td align="right">4,04</td>      <td>0</td>      <td>RB</td>      <td>R369</td>      <td>CR1</td>      <td>2</td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>02/04/2012</td>      <td>8000000003</td>      <td>#Ditta XYZ Srl</td>      <td>00/4</td>      <td>02/02/2012</td>      <td align="right">121,00</td>      <td>0</td>      <td>BB</td>      <td>BB60</td>      <td></td>      <td>4</td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>08/04/2012</td>      <td>8000000005</td>      <td>Ditta nuova tutta per me</td>      <td>00/5</td>      <td>08/02/2012</td>      <td align="right">32,06</td>      <td>0</td>      <td>BB</td>      <td>BB36</td>      <td></td>      <td>5</td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>08/03/2012</td>      <td>8000000005</td>      <td>Ditta nuova tutta per me</td>      <td>00/5</td>      <td>08/02/2012</td>      <td align="right">32,07</td>      <td>0</td>      <td>BB</td>      <td>BB36</td>      <td></td>      <td>5</td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>31/03/2012</td>      <td>8000000001</td>      <td>#Cliente di Prova</td>      <td>00/6</td>      <td>20/01/2012</td>      <td align="right">-4,03</td>      <td>0</td>      <td>RB</td>      <td>R369</td>      <td>CR1</td>      <td>6</td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>30/04/2012</td>      <td>8000000001</td>      <td>#Cliente di Prova</td>      <td>00/6</td>      <td>20/01/2012</td>      <td align="right">-4,03</td>      <td>0</td>      <td>RB</td>      <td>R369</td>      <td>CR1</td>      <td>6</td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>02/02/2012</td>      <td>8000000001</td>      <td>#Cliente di Prova</td>      <td>I 00/1</td>      <td>02/01/2012</td>      <td align="right">36,29</td>      <td>0</td>      <td></td>      <td></td>      <td></td>      <td></td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>    <tr>      <td>01/04/2012</td>      <td>8000000004</td>      <td>#Azienda agricola Metanolo &amp; Vino</td>      <td>I 00/3</td>      <td>03/03/2012</td>      <td align="right">6,05</td>      <td>0</td>      <td></td>      <td></td>      <td></td>      <td></td>      <td> NESSUN ALLEGATO PDF      </td>     </tr>  </tbody></table></div>

What's wrong?

**Comment by XinYiMan** [comment]
var renderCell = function (x, y, width, height, key, value, row, settings) {

            if (key == 'IMPORTO') {
		
/ *
WHAT DO I HAVE TO WRITE HERE TO ALIGN TEXT RIGHT
* /

            }

    };

**Comment by someatoms** [comment]
You seem to use `overflowColumns` correctly. However you need to specify the columns that you want to overflow and **not** the ones that you want to display in full content. In your case that would mean specifying every column, but not `CODICE`.

Did you look at the `custom style` example for the right alignment? It's quite complicated to achieve right now but copy and pasted from the example you would have to do something like this.

    if (key === 'IMPORTO') {
        var strWidth = doc.getStringUnitWidth('' + value) * doc.internal.getFontSize();
        x += width;
        x -= 2 * settings.padding;
        x -= strWidth;
    }

Hope that helps!

**Comment by XinYiMan** [comment]
Not found with this

                    var options = {renderHeader: header, renderFooter:
footer, margins: {horizontal: 40, top: 80, bottom: 50,overflowColumns:
['DATASCAD',
'DESCRIZIONE','NUMDOC','DATADOC','IMPORTO','ABILITA_PAG','TIPOPAG','CONDPAGAM','COD_BANCA','PROTOCOLLO']}};


Why?

2015-05-01 11:27 GMT+02:00 Simon Bengtsson <notifications@github.com>:

**Comment by XinYiMan** [comment]
Complete function, but not found 


			function generatefromtable(intestazione) {
				try{
					var $ret=true;
					var totalPagesExp = "{total_pages_count_string}";
				    //var doc = new jsPDF('p', 'pt');
					var doc = new jsPDF('l', 'pt', 'a4', true); 
				    var header = function (doc, pageCount, options) {
					doc.setFontSize(20);
					doc.text(intestazione, options.margins.horizontal, 60);
					doc.setFontSize(options.fontSize);
				    };

				    var renderCell = function (x, y, width, height, key, value, row, settings) {
					if (key === 'IMPORTO') {
					    var strWidth = doc.getStringUnitWidth('' + value) * doc.internal.getFontSize();
					    x += width;
					    x -= 2 * settings.padding;
					    x -= strWidth;
					}

				    };

				    var footer = function (doc, lastCellPos, pageCount, options) {
					var str = " " + pageCount + "/" + totalPagesExp;
					doc.text(str, options.margins.horizontal, doc.internal.pageSize.height - 30);
				    };
				    var options = {renderHeader: header, renderFooter: footer, margins: {horizontal: 40, top: 80, bottom: 50, renderCell: renderCell,overflowColumns: ['DATASCAD', 'DESCRIZIONE','NUMDOC','DATADOC','IMPORTO','ABILITA_PAG','TIPOPAG','CONDPAGAM','COD_BANCA','PROTOCOLLO']}};    

				    // Be sure to set the second parameter (indexBased option) to true
				    // It will be the default behavior in v2.0, but are now behind an option for compatibility
				    var res = doc.autoTableHtmlToJson(document.getElementById("tbl_daStampare"), true);

				    doc.autoTable(res.columns, res.data, options);
   				    doc.putTotalPages(totalPagesExp);

				    doc.output("dataurlnewwindow");

				}catch(err) {
			    		//err.message per avere il testo del messaggio
					ret=false;
				}

				return ret;
			}

**Comment by someatoms** [comment]
What do you mean with not found? Can you create a new or fork the jsfiddle I posted in the other issue and replicate the issue?

**Comment by XinYiMan** [comment]
https://jsfiddle.net/wo6rgq8z/1/

2015-05-01 12:52 GMT+02:00 Simon Bengtsson <notifications@github.com>:

**Comment by someatoms** [comment]
In that jsFiddle the table element you provide to the `autoTableHtmlToJson` function is `null`.

**Comment by XinYiMan** [comment]
I do not understand how I should change the code?

2015-05-01 18:24 GMT+02:00 Simon Bengtsson <notifications@github.com>:

**Comment by someatoms** [comment]
Try to reproduce the issue by creating a working jsfiddle. Right now I don't have time to look into this specifically at the moment. Right aligned columns are shown how to implement in the custom style example and displaying some columsn in full is shown in the long text example so it might help you to check those out and base your code on them if necessary.

**Comment by someatoms** [comment]
Did you solve your issue?

**Comment by XinYiMan** [comment]
I have not yet solved. Now using your example, you get a blank column. I am
attaching the pdf and the code that realizes.
You know help me?

Code:

            function generatefromtable(intestazione) {
                try{
                    var $ret=true;
                    var totalPagesExp = "{total_pages_count_string}";
                    //var doc = new jsPDF('p', 'pt');
                    var doc = new jsPDF('l', 'pt', 'a4', true);
                    var header = function (doc, pageCount, options) {
                    doc.setFontSize(20);
                    doc.text(intestazione, options.margins.horizontal, 60);
                    doc.setFontSize(options.fontSize);
                    };

                    var renderCell = function (x, y, width, height, key,
value, row, settings) {
                    if (key === 5) {
                        var strWidth = doc.getStringUnitWidth('' + value) *
doc.internal.getFontSize();
                        x += width;
                        x -= 2 * settings.padding;
                        x -= strWidth;
                    }        // Others
                    else {
                        doc.rect(x, y, width, height, 'S');
                        y += settings.lineHeight / 2 +
doc.internal.getLineHeight() / 2 - 2.5;
                        doc.text('' + value, x + settings.padding, y);
                    }


                    };

                    var footer = function (doc, lastCellPos, pageCount,
options) {
                    var str = " " + pageCount + "/" + totalPagesExp;
                    doc.text(str, options.margins.horizontal,
doc.internal.pageSize.height - 30);
                    };
                    var options = {renderHeader: header, renderFooter:
footer, renderCell: renderCell, margins: {horizontal: 40, top: 80, bottom:
50,overflowColumns: ['DATASCAD',
'DESCRIZIONE','NUMDOC','DATADOC','IMPORTO','ABILITA_PAG','TIPOPAG','CONDPAGAM','COD_BANCA','PROTOCOLLO']}};


                    // Be sure to set the second parameter (indexBased
option) to true
                    // It will be the default behavior in v2.0, but are now
behind an option for compatibility
                    var res =
doc.autoTableHtmlToJson(document.getElementById("tbl_daStampare"), true);

                    doc.autoTable(res.columns, res.data, options);
                       doc.putTotalPages(totalPagesExp);

                    doc.output("dataurlnewwindow");

                }catch(err) {
                        //err.message per avere il testo del messaggio
                    ret=false;
                }

                return ret;
            }




2015-05-08 0:06 GMT+02:00 Simon Bengtsson <notifications@github.com>:

**Comment by XinYiMan** [comment]
News?!

**Comment by someatoms** [comment]
You had an issue with your renderCell method. Try this instead

    var renderCell = function (x, y, width, height, key, value, row, settings) {

        doc.rect(x, y, width, height, 'S');

        if (key === 5) {
            var strWidth = doc.getStringUnitWidth('' + value) *
                doc.internal.getFontSize();
            x += width;
            x -= 2 * settings.padding;
            x -= strWidth;
        }

        y += settings.lineHeight / 2 +
        doc.internal.getLineHeight() / 2 - 2.5;
        doc.text('' + value, x + settings.padding, y);

    };

Here is a working [jsfiddle](https://jsfiddle.net/someatoms/mhzex91n/3/)

**Comment by XinYiMan** [comment]
Thank you.
You are angel :)

2015-05-14 23:00 GMT+02:00 Simon Bengtsson <notifications@github.com>:

**Comment by someatoms** [comment]
No worries, let me know if you have other issues!

**Comment by leahwolfe** [comment]
I too would love to get help with aligning columns.  the working fiddle is no longer good.

**Comment by sudarshan211** [comment]
how to add extra content in generated pdf after table
