### ISSUE TITLE
Tables side by side

### ISSUE THREAD

**Issue by Urr4** [someatoms/jsPDF-AutoTable#30]
Is it possible to get two or more tables side by side?

**Comment by someatoms** [comment]
Sure! Check out the [multiple tables](https://someatoms.github.io/jsPDF-AutoTable/#multiple) example. It involves playing with `margins` and `startY`, like this: 

    doc.autoTable(columns, data, {
        startY: 80,
        avoidPageSplit: true,
        margins: {left: 10, right: 300, top: 60, bottom: 40},
        fontSize: 8
    });

    doc.autoTable(columns, data, {
        startY: 80,
        avoidPageSplit: true,
        margins: {left: 300, right: 10, top: 60, bottom: 40},
        fontSize: 8
    });

**Comment by someatoms** [comment]
Sure, you would have to play with`} margins and the `startypos`
