### ISSUE TITLE
doc.getStringUnitWidth is not a function

### ISSUE THREAD

**Issue by daniel-lizik** [someatoms/jsPDF-AutoTable#34]
Line 352 calls for doc.getStringUnitWidth but this does not appear to be a method of the doc object?

    var strWidth = doc.getStringUnitWidth(txt) * doc.internal.getFontSize();

 If I console.log the doc object here's what I get:

![jspdf](https://cloud.githubusercontent.com/assets/10506366/7773265/53c13a94-0071-11e5-8b73-b3405225d17b.PNG)

I'm using jsPDF 0.9.0rc2 downloaded from the jsPDF site, but there is no `getStringUnitWidth` method in their source either. Am I missing some other plugin dependency? I've included this in my html head but I doubt this affects my problem:

    <script src="/vendor/jspdf.js"></script>
    <script src="/vendor/jspdf.plugin.autotable.js"></script>

I could add in a single module to the jspdf object, but I'm not sure where to find the getStringUnitWidth method. Any advice?

**Comment by daniel-lizik** [comment]
Ok I found it, you have to include jspdf.plugin.split_text_to_size.js in your dependencies as well

**Comment by someatoms** [comment]
I should probably mention that in the README. However, I would recommend using one of the dist files from github since they bundle some Möre useful plugins and are at the latest version 1.1
