### ISSUE TITLE
columns data trucated html table to pdf 

### ISSUE THREAD

**Issue by ruhijain** [someatoms/jsPDF-AutoTable#37]
Hi,

I could not get overflow: linebreak to work for me. I have data as HTML, I convert it to json using autoTableHtmlToJson and then use autoTable to generate the PDF.

For example:

var res = doc.autoTableHtmlToJson(document.getElementById("basic-table"), true);

doc.autoTable(res.columns, res.data, {margins: {horizontal: 10, top: 40, bottom: 40}, startY: 370, overflow: 'linebreak', overflowColumns: false});

publish(doc.output('datauristring'));

But the column data gets truncated instead of getting word wrapped. How to achieve it?

**Comment by someatoms** [comment]
I found a bug just now that means that the overflowColumns  option has to be specifued in order for linebreak to work. I will fix it as son as possible, but in the mean time you can simply specify it.

**Comment by ruhijain** [comment]
If i specify overflow columns, It does not increase the height of row dynamically, but it increases the cell width which causes my table to extend out of the page :(

How can i achieve something similar to the last table shown in longData example considering i dnt have the json data, I have html data.

**Comment by someatoms** [comment]
I just published a fix in the latest version [1.3.1](https://github.com/someatoms/jsPDF-AutoTable/releases/tag/1.3.19). Let me know if it works for you now!

**Comment by ruhijain** [comment]
Link seems to be broken..

**Comment by ruhijain** [comment]
Awesome its working.. Just one more thing the table headers are not wrapped still. Anything i have missed? How to get that working?

**Comment by someatoms** [comment]
Sweet! Header linebreaks are not supported right now unfortunately.

**Comment by ruhijain** [comment]
Is there any workaround for that. I mean <th> is quite similar to <td>, I need to have the header row visible properly. Let me know if there is anything i can play with to get this working. I would really appreciate.

**Comment by ankur2728** [comment]
It is wonderful. That worked. But again linebreaks on headers are not working. Please let me know any workaround. I am using th has header. Can use td instead of th. Will it work.? Please assist.

**Comment by ruhijain** [comment]
Tried using td instead of th. Does not work. It seems the first row is always taken as columns.

Putting the headers in simply a row works but then it needs to have some formatting options to set background color to differentiate it normal rows. But again there  is no way to remove the default header that is to have just the data not the columns.

**Comment by someatoms** [comment]
You can style the first row using the renderCell option. And I think setting the headers to false will disable the header row.

**Comment by ankur2728** [comment]
Hi Ruhi,

Please do let me know if that workaround works. And possibly if you can share the code. Thanks in advance.

**Comment by ruhijain** [comment]
Tried setting columns parameter to false, The header is still displayed and header text become 0..1..2...3..4 :(

**Comment by ruhijain** [comment]
Somehow i removed the header by setting its width and height to 0 from renderHeaderCell.

But there are two problems still:

1. How to achieve having header row on everypage if i want to use first row as header?
2. How to renderCell for background color for only top row in all the pages?

The best preferred solution would be to have line break option for header  too. Other workaround require too much of extra work.

**Comment by someatoms** [comment]
Then I think the easiest way would be to change the plugin code. It wouldn't be too hard, but I won't be able to do it for a few days probably. If you end up doing it, be sure to send a pull request!

**Comment by ruhijain** [comment]
Unfortunately I am pretty new in Javascript. I have figured out that printHeader is the function i may have to modify, but it looks quite hard to play around with the code being not an expert in it. I would try but can you tell me by what time you could come with a fix for this?

**Comment by someatoms** [comment]
Some day this week, hopefully tonight, worst case sunday.

**Comment by ruhijain** [comment]
Cool, I would better wait for it and i wish you do not have to go for the worst case :). Thanks a lot for responding so quickly to this.

**Comment by ruhijain** [comment]
Ankur,
Are you also working over the header text wrapping issue. Let me know if you find a fix for this.  It is kind of urgent for me.

**Comment by ankur2728** [comment]
Ruhi,

I can solve this, but problem is time. I have left it as it is and working on other tasks. But i have to solve this till this friday. If we do not get the fix then i will look into this on friday or saturday in worst case.

Thanks
Ankur Garg

**Comment by ruhijain** [comment]
Thanks Ankur, 

The same case is with me. Need to get this fixed by Friday. But since i am not an expert in javascript, It would be tricky for me to modify the plugin code. Let me know if you are able to find a fix.

Meanwhile i would also wait for Simon's fix.

**Comment by ankur2728** [comment]
Okay. But i must say this is a wonderful plugin. I tried many others as well. Just looking for this final fix. But did you try any of plugins or normal jspdf in IE 11. In IE11 none is working. Not able to download the file in IE11. Simons, please let me know if you have ever tried to save pdf in IE11

Thanks

**Comment by ruhijain** [comment]
No, My requirement is little different. I am a mobile developer so i am using it one of my iPad application.

**Comment by someatoms** [comment]
A fix for linebreak in headers is up in the latest version! Sorry for the delay. 

@ankur2728 I have tried it in IE, but not for a while. Please post an issue if it is not working for you. My plan is to support IE10+.

**Comment by ankur2728** [comment]
Hi,

Thanks for fix.I will try that out. 

Thanks
Ankur Garg

**Comment by ankur2728** [comment]
And to apply linebreak on header. Is there anything we need to do.

**Comment by ankur2728** [comment]
Thanks its working. Wonderful. You have been very supportive. This is a really wonderful plugin. Recommended

**Comment by someatoms** [comment]
Thanks!

**Comment by ruhijain** [comment]
Awesome!!  That works :) Thanks a lot for the quick update. Keep up the good work.

**Comment by sureeebabu** [comment]
how can i disable header jspdf autotable

**Comment by AadiHarsha** [comment]
Hello, Could you please let me know while exporting HTML data table remove specific column like Action below. 
![remove edit action column](https://user-images.githubusercontent.com/20493577/50530041-f8424700-0af1-11e9-9f45-051fde3efce8.PNG)

Please suggest.

**Comment by AadiHarsha** [comment]
Tried to customize below but not working.
$('#btnPDFReport').on('click', function () {
        $("#dataTable").tableHTMLExport({
            type: 'pdf', 
            filename: 'ExportToPDF.pdf',
            ignoreColumns: 'Action',
            //ignoreColumns: 'Action.ignore',
           // ignoreRows: '.ignore'      
 });
