### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by ankur2728** [someatoms/jsPDF-AutoTable#38]
Hi,

I am not able to download the file in IE11. It gives the prompt to download but. Then comes it couldn;t download. this is just not happening with your plugin but with normal jspdf as well. It seems file download problem exists with IE 11. Please let me know the solution.

Thanks
Ankur Garg

**Comment by someatoms** [comment]
It seems like the jsPDF library is using a syntax not supported by IE. It is seems really unnecessary as I think they could pretty easily change that, but unfortunately it is not much I can do.

**Comment by ankur2728** [comment]
Hi Simon. If you know the fix to make it work in IE 11. Please help.

Thanks

**Comment by someatoms** [comment]
I think it would require changes in the jspdf library so I don't know of an easy fix unfortunately. Hopefully you can get some response for the issue you posted in that repository.

**Comment by someatoms** [comment]
The latest preview version 1.1 still doesn't have IE support. However version 0.9 and 1.0 do. The latest release of this plugin should work with both those versions. Just tried in IE11.
