### ISSUE TITLE
Min width for pdf width

### ISSUE THREAD

**Issue by run-el** [someatoms/jsPDF-AutoTable#4]
I have a lot of columns and it's being cut off.. How can I fix that? Is there something like min width option for this?

**Comment by agarcia17** [comment]
any progress on this issue? maybe lower the font size to the size that will allow the columns to fit?

**Comment by someatoms** [comment]
In the latest release (made today...) the table is forced to never be larger than the page by ellipsing column texts that are too long. Take a look and see if that is a good fit for your project. You can however also lower the font size, line height and padding manually to get room for more text and columns. I added  new examples of these features in the examples folder.

You can attach the specific data that you want to display and I might be able to optimize for it. Closing the issue for now, but feel free to reopen if you are still having troubles.
