### ISSUE TITLE
Sub header colspan

### ISSUE THREAD

**Issue by lobosan** [someatoms/jsPDF-AutoTable#42]
Hi, I want to add a sub header to my table but instead of adding a new row, the row where I want to put the sub header it's being replaced. I noticed that in the example is doing the same. Is there any way to add the sub header without replacing any row?

**Comment by someatoms** [comment]
I'm working on better support for col and rowspans, in the meantime this is quite complicated. I think it would be possible to not override any rows by keeping track of the y pos that gets sent to the renderCell function and increase it sufficiently before drawing anything. I will look into this hopefully later today or this weekend if you have not solved it.

I have actually never used row- or colspan in a project, can you post what your data looks like so that I better can understand your use case?

**Comment by lobosan** [comment]
Hi Simon, thanks for your quick response. This is an abstract of my data. In some cases I have 60 objects and I need the sub headers to visualise groups of data, otherwise the readability isn't good. 

In the meantime, do you think is a good idea to add a new object for each sub header that I want to add so then that will be replaced with the correct colspan format?

Thanks in advance for your help.
```javascript
var data = [
    {title: "Fecha de creación", organization0: "2015-06-18", organization1: "2015-06-18"},
    {title: "Provincia", organization0: "Pichincha", organization1: "Imbabura"},
    {title: "Cantón", organization0: "Alausí", organization1: "Archidona"},
    {title: "Parroquia", organization0: "Achupallas", organization1: "Abdón Calderón"},
    {title: "Sector/es", organization0: "La Independencia", organization1: "La Independencia"},
    {title: "Nombre del grupo", organization0: "La lucha de los pobres", organization1: "Alternativas de desarrollo"},
    {title: "Representante", organization0: "Juan Guillén", organization1: "Juan Guillén"},
    // ADD SUB HEADER WITHOUT REPLACING A ROW
    {title: "Conocimientos de los pri...ales de la agroecología", organization0: 6, organization1: 9},
    {title: "Decisión política", organization0: 4, organization1: 6},
    {title: "Diseño de finca", organization0: 8, organization1: 8},
    {title: "Capacidades técnicas", organization0: 1, organization1: 6}
];
```

**Comment by someatoms** [comment]
Yes, that sounds like a good idea to add extra objects until version 2.0 of the library is out. Hopefully sometime soon. Should be a lot easier to work with col and rowspans in that version.

**Comment by someatoms** [comment]
Yes it sounds like a good idea to add extra objects for now. Is it something like this you want to accomplish with the sub header?  ![Table with subheader](https://www.packtpub.com/sites/default/files/Article-Images/jquery-article2-14.png)

**Comment by lobosan** [comment]
Hi Simon, yes that's what I needed and I solved it adding a new object for each sub header. I reported another issue https://github.com/someatoms/jsPDF-AutoTable/issues/44 where you can see the screeshot. However the problem on that issue is about linebreak but still not able to solve it. Hope you can help me with that one.

Thanks in advance for your help

**Comment by thaneshgopal** [comment]
Thank you for this plugin!  I am having an issue where the pageBreak : 'avoid' option doesn't work.  The following two tables comes up in two separate pages, I want to have it in the same page one after the other.  
I am sure, I am missing something.  Any help would be much appreciated.  
    pdf.autoTable(descTitle,  descData, {
            startY: 30,
            pageBreak:'avoid'
           });
       
        pdf.autoTable(titles,  data, {
            startY: 150,
            pageBreak:'avoid'
          });
        pdf.save("Report.pdf");

**Comment by simonbengtsson** [comment]
If you want the tables on the same page you should use pagebreak: 'auto'.  This is the default value however. That doesn't work either?

**Comment by thaneshgopal** [comment]
Thank you very much for the prompt reply Simon.  Yes, it is working.  sorry, I did not try that option before trying.  It is a great plugin and I am sure many people would find it useful!

**Comment by simonbengtsson** [comment]
No worries and thanks!

**Comment by thaneshgopal** [comment]
Hi Simon, 
Is there a way to generate a footer for the table.  Basically, I want to 
have something similar to the one below.  Thank you very much.
------------------------------------------------------------------
ID    | Name          | Number   | email 
------------------------------------------------------------------
123 | John Doe    | 123-2567 | jdoe@example.com
234 | Mike Smith  | 234-7890 | msmith@example.com
-------------------------------------------------------------------
Total | 2
-------------------------------------------------------------------

**Comment by thaneshgopal** [comment]
Hi Simon,
Is there a way to generate a footer for the table. Basically, I want to
have something similar to the one below. Thank you very much.
ID | Name | Number | email

123 | John Doe | 123-2567 | jdoe@example.com
234 | Mike Smith | 234-7890 | msmith@example.com
Total | 2

**Comment by thaneshgopal** [comment]
Hi Simon, 
I am also looking to add a sub header exactly as the image you posted above.  Is there an example that exist for doing similar thing?  Thank you.
