### ISSUE TITLE
Right align few columns

### ISSUE THREAD

**Issue by ankur2728** [someatoms/jsPDF-AutoTable#48]
Hi,

Can we right align any column header and data. Please respond asap. need it very urgently if it is possible

Thanks

**Comment by someatoms** [comment]
Yes! You have to do it yourself however in the drawCell function like in the custom style [example](https://github.com/someatoms/jsPDF-AutoTable/blob/master/examples/examples.js) ([demo](https://someatoms.github.io/jsPDF-AutoTable/#custom)).

**Comment by ankur2728** [comment]
Thanks for your quick response. Which code block this represents.

**Comment by someatoms** [comment]
Check for `if (key === 'expenses') {`

**Comment by ankur2728** [comment]
I tried the code. Its working but linebreaks are failing coz of this code.

**Comment by someatoms** [comment]
Try the solution in #43. I will update the examples as soon as possible with this fix.

**Comment by someatoms** [comment]
Marking this as an enhancement as it will be easier to add right aligned columns in version 2.0 which I'm at work on now.

**Comment by someatoms** [comment]
Version 2.0 is now released and this is now easy to do using the `halign` style set to `right`.
