### ISSUE TITLE
How to add page header with addHTML ?

### ISSUE THREAD

**Issue by danieldacruzferreira** [someatoms/jsPDF-AutoTable#51]
I tried to add header in PDF pages with the addHTML() jsPDF function, but this not works, this is my code:

            var totalPagesExp = "{total_pages_count_string}";
	    var doc = new jsPDF('p', 'pt');
	    
	    var htmlHeader = $(".report-container header")[0];
	    
	    var header = function (docPage, pageCount, options) {
	        
	    	docPage.addHTML(htmlHeader, null, function(){
	        	
	        });
	    };
	    
	    var footer = function (doc, lastCellPos, pageCount, options) {
	        var str = "Page " + pageCount;
	        // Total page number plugin only available in jspdf v1.0+
	        if (typeof doc.putTotalPages === 'function') {
	            str = str + " of " + totalPagesExp;
	        }
	        doc.text(str, options.margins.horizontal, doc.internal.pageSize.height - 30);
	    };
	    var options = {renderHeader: header, renderFooter: footer, margins: {horizontal: 40, top: 80, bottom: 50}};
	   

		doc.autoTable(columns, data, options);
	    
		// Total page number plugin only available in jspdf v1.0+
		if (typeof doc.putTotalPages === 'function') {
		     doc.putTotalPages(totalPagesExp);
		}
	   
	    doc.save('table.pdf');

**Comment by someatoms** [comment]
You should be able to use any jspdf function in the header and footer functions, including `addHTML`.  I haven't used that function myself however. Do you get an error message?

**Comment by danieldacruzferreira** [comment]
Hello
I don't get any error, the header is blank.
I noticed that the addHtml() inside the header function runs after doc.save ('table.pdf'). That is, addHTML() runs only after the PDF is ready.

My test:

            var totalPagesExp = "{total_pages_count_string}";
	    var doc = new jsPDF('p', 'pt');
	    
	    var htmlHeader = $(".report-container header")[0];
	    
	    var header = function (docPage, pageCount, options) {
	        
	    	docPage.addHTML(htmlHeader, null, function(){
	        	
	    		console.log("adding header");
	        
	    	});
	    };
	    
	    var footer = function (doc, lastCellPos, pageCount, options) {
	    var str = "Page " + pageCount;
	        // Total page number plugin only available in jspdf v1.0+
	        if (typeof doc.putTotalPages === 'function') {
	            str = str + " of " + totalPagesExp;
	        }
	        doc.text(str, options.margins.horizontal, doc.internal.pageSize.height - 30);
	    };
	    var options = {renderHeader: header, renderFooter: footer, margins: {horizontal: 40, top: 80, bottom: 50}};
	   

		doc.autoTable(columns, data, options);
	    
		// Total page number plugin only available in jspdf v1.0+
		if (typeof doc.putTotalPages === 'function') {
		     doc.putTotalPages(totalPagesExp);
		}
	   
		console.log("saving pdf");
		
	         doc.save('table.pdf');

Firebug console output:

saving pdf
(4) adding header (called 4 times, once per page)

**Comment by someatoms** [comment]
I read some about the addHTML function add it seems like you have to use it like this

    var pdf = new jsPDF('p','pt','a4');
    pdf.addHTML(document.body,function() {
        pdf.save('web.pdf');
    });

Unfortunaletly that means that you can't use it in the renderHeader or renderFooter functions afterall. Sorry for the confusing answer above.

**Comment by danieldacruzferreira** [comment]
OK, I'll try some other way
Thank you :)
