### ISSUE TITLE
Respect HTML cell width

### ISSUE THREAD

**Issue by mbn92** [someatoms/jsPDF-AutoTable#55]
Hi,

I recently ran by this project which looked like it would fit my needs, but now i hit a wall when I am trying to generate a tabel from HTML code.

I'm generating a table from a list of materials and at the bottom I would like a total-line, which sums it all up. Every element consists of a type, descrtiption, unit, amount, price and I would like the sum to lokke like this: 

http://puu.sh/j7oAi/2c864c7e5a.png

But end up with: 

http://puu.sh/j7oBM/e97d392266.png

Is it possible for it to respect the widths specified in the HTML code, or some other way aorund this?

Thanks

**Comment by wilarz89** [comment]
How do you generate a table from html do yo do it recursively

**Comment by someatoms** [comment]
Unfortunately no, it is not possible to transfer the width of the html table columns at this moment. However, you can specify the widths manually or specify that certain columns should not be subjected to the overflow method. Check out the README and the examples for information about how to do this.

Sorry for the late answer.

**Comment by mbn92** [comment]
No worries, ended doing it from dataobjects insted :)

**Comment by someatoms** [comment]
Great!
