### ISSUE TITLE
Getting the error doc.autoTable is undefined. Using node and angular.js

### ISSUE THREAD

**Issue by maulikkothari92** [someatoms/jsPDF-AutoTable#56]

**Comment by mbn92** [comment]
Hi,

Do you have all the needed scripts included? 

Try pasting your code here :)

**Comment by maulikkothari92** [comment]
Same as demo :
HTML code- 
<a style="float: right; padding-right: 0.3cm;"  href="javascript:printChallan()" class="btn btn-xs btn-success">Print Challan</a>  
Javascript code - 
function printChallan() {     
        var columns = [
            {title: "ID", key: "id"},
            {title: "Name", key: "name"}, 
            {title: "Country", key: "country"}, 
            {title: "Email", key: "email"}
        ];
        var data = [
            {"id": 1, "name": "Shaw", "country": "Tanzania", "email": "abrown@avamba.info"},
            {"id": 2, "name": "Nelson", "country": "Kazakhstan", "email": "jjordan@agivu.com"},
            {"id": 3, "name": "Garcia", "country": "Madagascar", "email": "jdean@skinte.biz"}
        ];

        var doc = new jsPDF('p', 'pt');
        doc.autoTable(columns, data, {});
        doc.save('table.pdf');

    }

Error: Uncaught TypeError: doc.autoTable is not a functionprintChallan @ VM864:31
(anonymous function) @ VM917:1

**Comment by someatoms** [comment]
Can you further explain your setup? For example how you are using node with angular and what your folder structure looks like?

**Comment by someatoms** [comment]
Closing this for now. Feel free to reopen if you are still having problems or post on stackoverflow with the tag jspdf-autotable.

**Comment by pavanshinde47** [comment]
doc.autoTable is not a function how to get rid of this error

**Comment by simonbengtsson** [comment]
Feel free opening a new issue with the code you are using. In general `doc.autoTable is not a function` means that there is some issues with how the scripts are included.

**Comment by pavanshinde47** [comment]
yepp, the jsPDF file included twise, now removed one and it seem to work .. thanks to guide.

**Comment by simonbengtsson** [comment]
Glad you solved it.
