### ISSUE TITLE
Cannot use a recursive method to print a table from a data source

### ISSUE THREAD

**Issue by wilarz89** [someatoms/jsPDF-AutoTable#58]
hello 

I tried to implement de generation o a pdf table recursively from a data base using a a controller and twig template.
i dont know if i am doing it wrong

but it does not work:

Sample:

<script>

    $(document).ready(function() {

      var doc = new jsPDF('p', 'pt');

      var columns = new Array();
      var data = new Array();

      {% for iteraProducto in listaProducto %}

        var id ="{{ iteraProducto.id }}";
        var nombre ="{{ iteraProducto.nombre }}";
        var fechaCreacion ="{{ iteraProducto.fechaCreacion|date('Y M d H s') }}";
        var descripcion ="{{ iteraProducto.descripcion }}";
        var valor ="{{ iteraProducto.valor }}";
        var iva ="{{ iteraProducto.iva }}";
        var fechaVencimiento =" {{ iteraProducto.fechaVencimiento|date('Y M d') }}";

         columns.push([
          {title: "ID", key: "id"},
          {title: "Nombre", key: "nombre"},
          {title: "Fecha Creacion", key: "fechaCreacion"},
          {title: "Descripcion", key: "descripcion"},
          {title: "Valor", key: "valor"},
          {title: "Iva", key: "iva"},
          {title: "Fecha Vencimiento", key: "fechaVencimiento"}]
         );

         data.push([
          {"id": id,
            "nombre": nombre,
            "fechaCreacion": fechaCreacion,
            "descripcion": descripcion,
            "valor":valor,
            "iva": iva,
            "fechaVencimiento": fechaVencimiento}]
         );

      {% endfor %}

      //TODO reemplazar por líneas que vengan desde el controlador
      doc.text(35, 25, "PRODUCTOS EN INVENTARIO");
      doc.autoTable(columns, data, {});
      //doc.save('table.pdf');

      var jIframe = $('#prueba');

      jIframe.attr('src', doc.output('dataurlstring'));

    })

  </script>

  <iframe id="prueba" style="width: 500px; height: 800px;"></iframe>

**Comment by wilarz89** [comment]
Could solve it ,had to get the columns value out of the for.

**Comment by someatoms** [comment]
Great!
