### ISSUE TITLE
Column Styles

### ISSUE THREAD

**Issue by BlueWater86** [someatoms/jsPDF-AutoTable#59]
I couldn't get column widths working so had a quick dig through your plugin. Looks like you have a dodgy line left in at line number 327. Set col.styles to empty object and then check if empty object contains a columnWidths member:

            var col = new Column(dataKey);
            col.styles = {};
            if (typeof col.styles.columnWidth === 'undefined') col.styles.columnWidth = 'auto';
            table.columns.push(col);

**Comment by someatoms** [comment]
Should be fixed now. Thanks!

**Comment by brahimkra** [comment]
Hi, i can't change background color of second column and this is my code:
 

> doc.autoTable(res.columns, res.data, {
>       styles: {lineWidth: 1,fillColor: [255, 255, 255] , // 'auto', 'wrap' or a number,
> 
> 
>       },
>       columnStyles: {
>         lineWidth: 1,
>         0: {columnWidth: 140,fillColor: [213,41,41]},
>         1: {columnWidth: 100,},
>         // etc
>       },
> 
>         margin: {top: 320,left:317},
>     });
>
