### ISSUE TITLE
Row is lost on page break

### ISSUE THREAD

**Issue by npetty** [someatoms/jsPDF-AutoTable#64]
Hello,

Great plugin. Really impressed!

I have run into an issue where a row of the table is lost when a page break occurs. Ran into on an angular.js site.

[jsFiddle here.](http://jsfiddle.net/npetty/c3vwkt7q/)

**Comment by someatoms** [comment]
Hi! Oops! Seems like some bugs were introduced in the last commit, reverted it now and this should be working now.

**Comment by npetty** [comment]
Great! Thanks for the prompt reply.
